version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: space-bio-backend:latest
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./abstracts_cache.json:/app/abstracts_cache.json
      - ./SB_publication_PMC.csv:/app/SB_publication_PMC.csv
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: space-bio-frontend:latest
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped
